import{a as l}from"./assets/vendor-a61d8330.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();l.defaults.headers.common["x-api-key"]="live_HiesbHCNozFabauA2TlzO2OtiyWGedKBWDRv7zZNtooEj53fuPidluKoVAklkZzU";const p=async()=>{try{return(await l.get("https://api.thecatapi.com/v1/breeds")).data}catch(t){console.error("Cannot fetch breeds. Error occured: ",t)}},f=async t=>{try{return(await l.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${t}`)).data}catch(r){console.error("Cannot fetch breed info. Error occured: ",r)}},a=document.querySelector(".breed-select"),u=document.querySelector(".cat-info"),s=document.querySelector(".loader"),d=document.querySelector(".error");d.style.display="none";const y=t=>{const r=t.breeds[0],n=`
        <img src="${t.url}" width="600" height="600" style="object-fit: contain;"/>
        <div>
            <h2>${r.name}</h2>
            <p>${r.description}</p>
            <ul>${r.temperament.split(", ").map(c=>`<li>${c}</li>`).join("")}</ul>
        </div>
    `;u.innerHTML="",u.insertAdjacentHTML("afterbegin",n)},m=async t=>{const r=t.target[a.selectedIndex];try{s.style.display="block";const n=await f(r.value);y(n[0]),s.style.display="none"}catch(n){s.style.display="none",d.style.display="block",console.error("Cannot render breed info. Error occured: ",n)}},h=async()=>{try{const r=(await p()).map(n=>`<option value="${n.id}">${n.name}</option>`).join("");a.insertAdjacentHTML("afterbegin",r),a.addEventListener("change",m),s.style.display="none"}catch(t){s.style.display="none",d.style.display="block",console.error("Cannot render breeds. Error occured: ",t)}};h();
//# sourceMappingURL=commonHelpers.js.map
