import{a as d,i as u,S as p}from"./assets/vendor-22d9b643.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();d.defaults.headers.common["x-api-key"]="live_HiesbHCNozFabauA2TlzO2OtiyWGedKBWDRv7zZNtooEj53fuPidluKoVAklkZzU";const h=async()=>{try{return(await d.get("https://api.thecatapi.com/v1/breeds")).data}catch(e){return u.error({title:"Error occured",message:"Cannot fetch breeds. Try to reload page!",timeout:!1}),console.error("Cannot fetch breeds. Error occured: ",e),[]}},y=async e=>{try{return(await d.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`)).data}catch(r){return u.error({title:"Error occured",message:"Cannot fetch breed info. Try to choose another breed or reload page!",timeout:!1}),console.error("Cannot fetch breed info. Error occured: ",r),[]}},l=document.querySelector(".cat-info"),f=document.querySelector(".loader"),i=document.querySelector(".breed-select"),m=()=>{f.classList.add("loader--visible")},c=()=>{f.classList.remove("loader--visible")},g=e=>{const r=e.breeds[0],n=`
        <img src="${e.url}" width="600" height="600" class="pic" />
        <div>
            <h2>${r.name}</h2>
            <p>${r.description}</p>
            <ul>${r.temperament.split(", ").map(s=>`<li>${s}</li>`).join("")}</ul>
        </div>
    `;l.innerHTML="",l.insertAdjacentHTML("afterbegin",n)},b=async e=>{const r=e.target[e.target.selectedIndex];try{m();const n=await y(r.value);g(n[0]),c()}catch(n){c(),console.error("Cannot render breed info. Error occured: ",n)}},v=e=>{const r=e.map(s=>`<option value="${s.id}">${s.name}</option>`).join("");i.insertAdjacentHTML("afterbegin",r);const n=new p({select:i});return i.addEventListener("change",b),n},L=async()=>{try{m();const e=await h(),r=v(e);c()}catch(e){c(),console.error("Cannot render breeds. Error occured: ",e)}};L();
//# sourceMappingURL=commonHelpers.js.map
